#include<stdio.h>
#include<iostream.h>
#include<conio.h>
#include<dos.h>
void main()
{
clrscr();
char a;
textcolor(12);
cprintf("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tGIRI CINEMAS\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
gotoxy(10,10);
cout<<"1)Now Playing \n";
gotoxy(12,11);
cout<<"a)Megaaman\n";
gotoxy(12,12);
cout<<"b)Mersal\n";
gotoxy(12,13);
cout<<"c)Eesaan\t\t\t\t";
gotoxy(30,10);
cout<<"2)Up coming";
gotoxy(30,11);
cout<<"a)Enthiran 2.0";
gotoxy(30,12);
cout<<"b)Baby boss";
gotoxy(30,13);
cout<<"c)Justice league";
//a=getch();
/*switch(a)
{
case 's': textcolor(12);
	  cprintf("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tGIRI CINEMAS\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
	  gotoxy(10,10);
	  cout<<"1)Now Playing \n";
	  gotoxy(12,11);
	  textbackground(12);
	  cprintf("a)Megaaman\n");
	  gotoxy(12,12);
	  cout<<"b)Mersal\n";
	  gotoxy(12,13);
	  cout<<"c)Eesaan\t\t\t\t";
	  gotoxy(30,10);
	  cout<<"2)Up coming";
	  gotoxy(30,11);
	  cout<<"a)Enthiran 2.0";
	  gotoxy(30,12);
	  cout<<"b)Baby boss";
	  gotoxy(30,13);
	  cout<<"c)Justice league";
	  */

for(int i=1;i<=6;i++)
{
  a=getch();
  clrscr();
  if(a=='s')
 {
	  textcolor(12);
	  cprintf("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tGIRI CINEMAS\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
	  gotoxy(10,10);
	  cout<<"1)Now Playing \n";
	  gotoxy(12,11);
	  textcolor(12);
	  cprintf("a)Megaaman\n");
	  gotoxy(12,12);
	  cout<<"b)Mersal\n";
	  gotoxy(12,13);
	  cout<<"c)Eesaan\t\t\t\t";
	  gotoxy(30,10);
	  cout<<"2)Up coming";
	  gotoxy(30,11);
	  cout<<"a)Enthiran 2.0";
	  gotoxy(30,12);
	  cout<<"b)Baby boss";
	  gotoxy(30,13);
	  cout<<"c)Justice league";



	  }

	  if((a=='s')&&(i==2))
	  {
	  clrscr();
	  textcolor(12);
	  cprintf("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tGIRI CINEMAS\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
	  gotoxy(10,10);
	  cout<<"1)Now Playing \n";
	  gotoxy(12,11);
	  //textbackground(12);
	  cout<<"a)Megaaman\n";
	  gotoxy(12,12);
	  textcolor(12);
	  cprintf("b)Mersal\n");
	  gotoxy(12,13);
	  cout<<"c)Eesaan\t\t\t\t";
	  gotoxy(30,10);
	  cout<<"2)Up coming";
	  gotoxy(30,11);
	  cout<<"a)Enthiran 2.0";
	  gotoxy(30,12);
	  cout<<"b)Baby boss";
	  gotoxy(30,13);
	  cout<<"c)Justice league";
	  }
	  if((a=='s')&&(i==3))
	  {
	   clrscr();
	  textcolor(12);
	  cprintf("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tGIRI CINEMAS\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
	  gotoxy(10,10);
	  cout<<"1)Now Playing \n";
	  gotoxy(12,11);
	  //textbackground(12);
	  cout<<"a)Megaaman\n";
	  gotoxy(12,12);
	  //textcolor(12);
	  cout<<"b)Mersal\n";
	  gotoxy(12,13);
	  textcolor(12);
	  cprintf("c)Eesaan");
	  gotoxy(30,10);
	  cout<<"2)Up coming";
	  gotoxy(30,11);
	  cout<<"a)Enthiran 2.0";
	  gotoxy(30,12);
	  cout<<"b)Baby boss";
	  gotoxy(30,13);
	  cout<<"c)Justice league";
	  }
	  if((a=='s')&&(i==4))
	  { clrscr();
	  textcolor(12);
	  cprintf("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tGIRI CINEMAS\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
	  gotoxy(10,10);
	  cout<<"1)Now Playing \n";
	  gotoxy(12,11);
	  //textbackground(12);
	  cout<<"a)Megaaman\n";
	  gotoxy(12,12);
	  //textcolor(12);
	  cout<<"b)Mersal\n";
	  gotoxy(12,13);
	  cout<<"c)Eesaan\t\t\t\t";
	  gotoxy(30,10);
	  cout<<"2)Up coming";
	  gotoxy(30,11);
	  textcolor(12);
	  cprintf("a)Enthiran 2.0");
	  gotoxy(30,12);
	  cout<<"b)Baby boss";
	  gotoxy(30,13);
	  cout<<"c)Justice league";
	  }
	  if((a=='s')&&(i==5))
	 {
	  clrscr();
	  textcolor(12);
	  cprintf("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tGIRI CINEMAS\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
	  gotoxy(10,10);
	  cout<<"1)Now Playing \n";
	  gotoxy(12,11);
	  //textbackground(12);
	  cout<<"a)Megaaman\n";
	  gotoxy(12,12);
	  //textcolor(12);
	  cout<<"b)Mersal\n";
	  gotoxy(12,13);
	  cout<<"c)Eesaan\t\t\t\t";
	  gotoxy(30,10);
	  cout<<"2)Up coming";
	  gotoxy(30,11);
	 // textcolor(12);
	  cout<<"a)Enthiran 2.0";
	  gotoxy(30,12);
	  textcolor(12);
	  cprintf("b)Baby boss");
	  gotoxy(30,13);
	  cout<<"c)Justice league";
	  }
	  if((a=='s')&&(i==6))
	  { clrscr();
	  textcolor(12);
	  cprintf("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tGIRI CINEMAS\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
	  gotoxy(10,10);
	  cout<<"1)Now Playing \n";
	  gotoxy(12,11);
	  //textbackground(12);
	  cout<<"a)Megaaman\n";
	  gotoxy(12,12);
	  //textcolor(12);
	  cout<<"b)Mersal\n";
	  gotoxy(12,13);
	  cout<<"c)Eesaan\t\t\t\t";
	  gotoxy(30,10);
	  cout<<"2)Up coming";
	  gotoxy(30,11);
	  //textcolor(12);
	  cout<<"a)Enthiran 2.0";
	  gotoxy(30,12);
	  cout<<"b)Baby boss";
	  gotoxy(30,13);
	  textcolor(12);
	  cprintf("c)Justice league");
	  }
	  }
getch();
}

